### ISSUE TITLE
Move to @valuelife.org email account

### ISSUE THREAD

**Issue by valuelife** [1yzo/value-life-foundation-donate#17]
To do item for @Noitidart

**Comment by valuelife** [comment]
@1yzo move all support email to info@valuelife.org

**Comment by Noitidart** [comment]
@1yzo I setup the account already, just need to make changes on the website text to reflect this.

**Comment by Noitidart** [comment]
@1yzo I don't see info@valuelife.org email anywhere on site. In the "Call Us" section you should make that 'Contact Us' and put the email there as well.

contact us needs to be more prominent. everything is done from my side - just make this more prominent and close. (i setup the email accounts on the host)
