### ISSUE TITLE
Three primary images update to weekly cycle

### ISSUE THREAD

**Issue by valuelife** [1yzo/value-life-foundation-donate#18]
Top should be - The banner we see here, make a collage:

![image](https://user-images.githubusercontent.com/42555747/44367722-6a8c8600-a485-11e8-922b-ff5f86485686.png)

Middle - Use hands from here:

![image](https://user-images.githubusercontent.com/42555747/44367973-2a79d300-a486-11e8-96fe-887fb0c9816d.png)

Bottom - Use this one:

![image](https://user-images.githubusercontent.com/42555747/44367995-42e9ed80-a486-11e8-8b35-bfd3e3c8d950.png)

**Comment by valuelife** [comment]
Make images cycle with the other images from the old website. Like this:

cycle at bottom:
https://unsplash.com/photos/SYXGrovkVMY

https://unsplash.com/photos/LyKtSrQhBuc

cycle at middle:
![image](https://user-images.githubusercontent.com/42555747/44368042-6ca31480-a486-11e8-89f1-5710e4e4002b.png)

https://unsplash.com/photos/T1ISDtNMqwI

https://unsplash.com/photos/wxruheY5nG8

cycle this at top:
![image](https://user-images.githubusercontent.com/42555747/44368056-77f64000-a486-11e8-810e-2ca4b2f9b069.png)

https://unsplash.com/photos/AweUC9wTnbs

**Comment by valuelife** [comment]
https://unsplash.com/photos/8qqYd1b_eAI

**Comment by valuelife** [comment]
https://unsplash.com/photos/6ner152Cc6c

**Comment by Noitidart** [comment]
@1yzo I'm working on this on imgcycle branch - https://github.com/1yzo/value-life-foundation-donate/tree/imgcycle
